### ISSUE TITLE
IllegalStateException on TextView.onKeyUp

### ISSUE THREAD

**Issue by jshernandez15** [jshernandez15/miso-4208#16]
Fatal exception
java.lang.IllegalStateException: focus search returned a view that wasn't able to take focus!
FATAL EXCEPTION: main
Process: com.habitrpg.android.habitica, PID: 7214
java.lang.IllegalStateException: focus search returned a view that wasn't able to take focus!
	at android.widget.TextView.onKeyUp(TextView.java:5930)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2643)
	at android.view.View.dispatchKeyEvent(View.java:8411)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
	at android.widget.ScrollView.dispatchKeyEvent(ScrollView.java:369)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1495)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2361)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1709)
	at android.app.Activity.dispatchKeyEvent(Activity.java:2702)
	at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:541)
	at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:319)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2276)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4020)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3982)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3713)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3874)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2208)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1849)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1840)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2185)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:122)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by jshernandez15** [comment]
[logcat.txt](https://github.com/jshernandez15/miso-4208/files/1395870/logcat.txt)
